spring.application.name=merchant-backend
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/merchantportal
spring.datasource.username=postgres
spring.datasource.password=1532
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true

app.jwt.secret=VGhpc0lzQVNlY3VyZUtleUZvckpXVEF1dGhlbnRpY2F0aW9uMTIzNDU2
app.jwt.expirationMs=6000000
app.jwt.refreshExpirationMs=604800000
spring.profiles.active=dev
# Custom path for the UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
# Custom path for the raw JSON docs
